name: Requirement unit tests workflow
on: push
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - id: requirement_test_pre_requisite_test
        if: hashFiles('tests/requirement_test') != ''
        uses:  splunk/requirement-files-unit-tests@v1.0.0
        with:
          input-files: tests/requirement_test/logs
      - name: Archive production artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test_*.txt
