##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-1-2020
##
##
name: sync-develop

on:
  push:
    branches: [test/add-secrets-to-repo]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Secrets
        uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            SNYK_TOKEN
            GH_TOKEN_ADMIN
            GH_USER_ADMIN
            PAT_CLATOOL
            RP_ENDPOINT
            RP_UUID
            SNYK_TOKEN
            VT_API_KEY
            AWS_ACCESS_KEY_ID
            AWS_DEFAULT_REGION
            AWS_SECRET_ACCESS_KEY
            SEMGREP_DEPLOYMENT_ID
            SEMGREP_PUBLISH_TOKEN
            SAUCE_IDENTIFIER
            SAUCE_PASSWORD
            SAUCE_USERNAME
          REPOSITORIES: |
            splunk/addon-factory-smartx-ui-test-library
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
          CONCURRENCY: 2
          REPOSITORIES_LIST_REGEX: true
        env:
          GH_TOKEN_ADMIN: ${{secrets.GH_TOKEN_ADMIN}}
          GH_USER_ADMIN: ${{secrets.GH_USER_ADMIN}}
          PAT_CLATOOL: ${{secrets.PAT_CLATOOL}}
          RP_ENDPOINT: ${{secrets.RP_ENDPOINT}}
          RP_UUID: ${{secrets.RP_UUID}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
          VT_API_KEY: ${{secrets.VT_API_KEY}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          SEMGREP_DEPLOYMENT_ID: ${{secrets.SEMGREP_DEPLOYMENT_ID}}
          SEMGREP_PUBLISH_TOKEN: ${{secrets.SEMGREP_PUBLISH_TOKEN}}
          SAUCE_IDENTIFIER: ${{secrets.SAUCE_IDENTIFIER}}
          SAUCE_PASSWORD: ${{secrets.SAUCE_PASSWORD}}
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
