##
## SPDX-FileCopyrightText: 2021 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-1-2020
##
##
name: sync-develop

on:
  push:
    branches: [develop]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Setup
        run: |
          pip3 install git+https://github.com/pixelb/crudini.git 
          pip3 install reuse

      - name: sync
        run: |
          export PR_SUFFIX=-${{ github.ref }}
          mkdir work || true
          echo $GH_TOKEN_ADMIN | gh auth login --with-token   
          git config  --global user.email "addonfactory@splunk.com"
          git config  --global user.name "addonfactory"
          python3 tools/sync.py
        env:
          GH_USER_ADMIN: ${{ secrets.GH_USER_ADMIN }}
          GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}
  secrets:
    runs-on: ubuntu-latest
    needs:
      - sync
    steps:
      - name: Sync Secrets
        uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            SNYK_TOKEN
            GH_TOKEN_ADMIN
            GH_USER_ADMIN
            PAT_CLATOOL
            RP_ENDPOINT
            RP_UUID
            SNYK_TOKEN
            VT_API_KEY
            AWS_ACCESS_KEY_ID
            AWS_DEFAULT_REGION
            AWS_SECRET_ACCESS_KEY
            SEMGREP_DEPLOYMENT_ID
            SEMGREP_PUBLISH_TOKEN
          REPOSITORIES: |
            splunk-dbx-add-on-for-*
            splunk/splunk-add-on-for-*
            splunk/dropbox-add-on-for-splunk
            splunk/dropbox-app-for-splunk
            splunk/seckit_sa_geolocation
            splunk/splunk-add-on-for-ucc-example
            splunk/splunk-add-on-for-ucc-example-ng
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
          CONCURRENCY: 2
          REPOSITORIES_LIST_REGEX: true
        env:
          GH_TOKEN_ADMIN: ${{secrets.GH_TOKEN_ADMIN}}
          GH_USER_ADMIN: ${{secrets.GH_USER_ADMIN}}
          PAT_CLATOOL: ${{secrets.PAT_CLATOOL}}
          RP_ENDPOINT: ${{secrets.RP_ENDPOINT}}
          RP_UUID: ${{secrets.RP_UUID}}
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
          VT_API_KEY: ${{secrets.VT_API_KEY}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          SEMGREP_DEPLOYMENT_ID: ${{secrets.SEMGREP_DEPLOYMENT_ID}}
          SEMGREP_PUBLISH_TOKEN: ${{secrets.SEMGREP_PUBLISH_TOKEN}}
